### ISSUE TITLE
fresh

### ISSUE THREAD

**Issue by murisi** [anoma/VampIR-Book#2]
Hi! Nice work - I'd been struggling to articulate some parts of Vamp-IR. Just some minor concerns/clarifications:
> `fresh` must be followed by a syntactically valid expression surrounded by parentheses

I think this got fixed maybe recently? The program `fresh 22 = 22;` now compiles for me on `main` branch.
> Anything called inside of `fresh` is essentially a black box to the circuit.

Agreed to an extent. A more precise statement of `fresh`'s operation might be that it suppresses/severs the constraint that its (single) argument is equal to its return value. That being said, constraints for everything inside `fresh` are still generated, just like constraints for things outside `fresh` are generated. So (very loosely speaking) `fresh` merely severs a connection between the expression tree containing the `fresh` call and the subtree inside the `fresh` call rather than completely erasing the constraints of the subtree.

For example, the following example results in a prover error because the `2=3` constraint inside `fresh` is still emitted:
```
def my22 () = { 2=3; 22 };
fresh (my22 ()) = 22;
```
> The `fresh` keyword

In light of the above, an argument could be made that `fresh` behaves more like an intrinsic/normal higher order function (like `fold` and `iter`) than a keyword. The Rust implementation shows that `fresh`'s argument is evaluated without special treatment. See also https://github.com/anoma/vamp-ir/pull/68 , where a minor bug that was preventing `fresh` being used as a value is fixed.

**Comment by AHartNtkn** [comment]
Thanks for the feedback. I've incorporated your description and updates into section 3-1.
